import CallRecordTable from "../components/CallRecordTable";
import PastCallRecord from "../components/PastCallRecord";

export const TABLE_DATA = [
  {
    name: "Chitra Nayak",
    agenda: "Taxation and budgeting plan",
    date: "1 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Lavanya Tripathi",
    agenda: "Quarter Planning",
    date: "2 August",
    actions: ["call", "cancel"],
  },
  {
    name: "Sonal Jain",
    agenda: "Customer Success",
    date: "3 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Karan Patel",
    agenda: "Lead Sync",
    date: "4 August",
    actions: ["call"],
  },
  {
    name: "Isha Kapoor",
    agenda: "Budget Planning",
    date: "5 August",
    actions: ["call", "calendar"],
  },
  {
    name: "Naveen Reddy",
    agenda: "DevOps Sync",
    date: "6 August",
    actions: [],
  },
  {
    name: "Geeta Iyer",
    agenda: "Frontend Review",
    date: "7 August",
    actions: ["call"],
  },
  {
    name: "Riya Kapoor",
    agenda: "Planning Sprint",
    date: "8 August",
    actions: ["call", "calendar"],
  },
  {
    name: "Prachi Malhotra",
    agenda: "Vendor Meeting",
    date: "9 August",
    actions: ["cancel"],
  },
  {
    name: "Simran Kaur",
    agenda: "Customer Feedback",
    date: "10 August",
    actions: ["call", "cancel"],
  },
  {
    name: "Kunal Puri",
    agenda: "CI/CD Review",
    date: "11 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Tanmay Desai",
    agenda: "Release Demo",
    date: "12 August",
    actions: [],
  },
  {
    name: "Mohit Bansal",
    agenda: "Hiring Review",
    date: "13 August",
    actions: ["call"],
  },
  {
    name: "Bhavesh Modi",
    agenda: "SEO Planning",
    date: "14 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Ritika Das",
    agenda: "Design Feedback",
    date: "15 August",
    actions: ["call", "cancel"],
  },
  {
    name: "Kriti Sharma",
    agenda: "Bug Triage",
    date: "16 August",
    actions: ["call", "calendar"],
  },
  {
    name: "Uday Kumar",
    agenda: "Marketing Budget",
    date: "17 August",
    actions: ["cancel"],
  },
  {
    name: "Shreya Menon",
    agenda: "UI Testing",
    date: "18 August",
    actions: ["call"],
  },
  {
    name: "Suman Raj",
    agenda: "Team Meeting",
    date: "19 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Jatin Arora",
    agenda: "Code Review",
    date: "20 August",
    actions: ["call", "calendar"],
  },
  {
    name: "Rajeev Rana",
    agenda: "Design Approval",
    date: "21 August",
    actions: ["call"],
  },
  {
    name: "Alok Chatterjee",
    agenda: "Hiring Feedback",
    date: "22 August",
    actions: [],
  },
  {
    name: "Trisha Ghosh",
    agenda: "UX Audit",
    date: "23 August",
    actions: ["call", "cancel"],
  },
  {
    name: "Sneha Rao",
    agenda: "Sales Pitch",
    date: "24 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Divyansh Tyagi",
    agenda: "Release Meeting",
    date: "25 August",
    actions: ["call"],
  },
  {
    name: "Nikhil Raj",
    agenda: "Performance Review",
    date: "26 August",
    actions: ["call", "calendar"],
  },
  {
    name: "Neeraj Kumar",
    agenda: "Product Strategy",
    date: "27 August",
    actions: ["call", "cancel"],
  },
  {
    name: "Pooja Saini",
    agenda: "Customer Call",
    date: "28 August",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Harshita Yadav",
    agenda: "Technical Training",
    date: "29 August",
    actions: [],
  },
  {
    name: "Deepak Goyal",
    agenda: "Infrastructure Audit",
    date: "30 August",
    actions: ["call", "calendar"],
  },
  {
    name: "Natasha Bedi",
    agenda: "Growth Hacking",
    date: "31 August",
    actions: ["cancel"],
  },
  {
    name: "Yash Agarwal",
    agenda: "Roadmap Discussion",
    date: "1 September",
    actions: ["call"],
  },
  {
    name: "Aarti Joshi",
    agenda: "Sprint Planning",
    date: "2 September",
    actions: ["call", "cancel"],
  },
  {
    name: "Ravi Mehta",
    agenda: "Marketing Campaign",
    date: "3 September",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Siddharth Rao",
    agenda: "Sprint Demo",
    date: "4 September",
    actions: [],
  },
  {
    name: "Ramesh Shah",
    agenda: "User Story Mapping",
    date: "5 September",
    actions: ["call"],
  },
  {
    name: "Divya Nair",
    agenda: "Customer Success",
    date: "6 September",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Manish Roy",
    agenda: "Quarterly Report",
    date: "7 September",
    actions: ["call", "calendar"],
  },
  {
    name: "Ananya Sen",
    agenda: "Project Kickoff",
    date: "8 September",
    actions: ["call"],
  },
  {
    name: "Kajal Mishra",
    agenda: "User Research",
    date: "9 September",
    actions: ["call", "cancel"],
  },
  {
    name: "Rohit Rawat",
    agenda: "Data Sync",
    date: "10 September",
    actions: ["cancel"],
  },
  {
    name: "Ankit Sharma",
    agenda: "Legal Review",
    date: "11 September",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Veer Arora",
    agenda: "Design Feedback",
    date: "12 September",
    actions: ["call", "calendar"],
  },
  {
    name: "Sonal Jain",
    agenda: "Customer Feedback",
    date: "13 September",
    actions: ["call"],
  },
  {
    name: "Kabir Malhotra",
    agenda: "Client Onboarding",
    date: "14 September",
    actions: [],
  },
  {
    name: "Payal Sinha",
    agenda: "Release Meeting",
    date: "15 September",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Meena Verma",
    agenda: "UI Testing",
    date: "16 September",
    actions: ["call", "calendar"],
  },
  {
    name: "Vikas Singh",
    agenda: "PR Review",
    date: "17 September",
    actions: ["call"],
  },
  {
    name: "Keshav Saxena",
    agenda: "Bug Triage",
    date: "18 September",
    actions: ["cancel"],
  },
  {
    name: "Aman Tiwari",
    agenda: "Backend Sync",
    date: "19 September",
    actions: ["call", "calendar"],
  },
  {
    name: "Monika Rani",
    agenda: "Team Meeting",
    date: "20 September",
    actions: ["call"],
  },
  {
    name: "Irfan Khan",
    agenda: "Customer Call",
    date: "21 September",
    actions: ["calendar", "cancel"],
  },
];
