import CallRecordTable from "../components/CallRecordTable";
import PastCallRecord from "../components/PastCallRecord";

export const TABLE_DATA = [
  {
    name: "Chitra Nayak",
    agenda: "Legal Review",
    date: "2025-08-01",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Lavanya Tripathi",
    agenda: "Quarter Planning",
    date: "2025-08-02",
    actions: ["call", "cancel"],
  },
  {
    name: "Sonal Jain",
    agenda: "Customer Success",
    date: "2025-08-03",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Karan Patel",
    agenda: "Lead Sync",
    date: "2025-08-04",
    actions: ["call"],
  },
  {
    name: "Isha Kapoor",
    agenda: "Budget Planning",
    date: "2025-08-05",
    actions: ["call", "calendar"],
  },
  {
    name: "Naveen Reddy",
    agenda: "DevOps Sync",
    date: "2025-08-06",
    actions: [],
  },
  {
    name: "Geeta Iyer",
    agenda: "Frontend Review",
    date: "2025-08-07",
    actions: ["call"],
  },
  {
    name: "Riya Kapoor",
    agenda: "Planning Sprint",
    date: "2025-08-08",
    actions: ["call", "calendar"],
  },
  {
    name: "Prachi Malhotra",
    agenda: "Vendor Meeting",
    date: "2025-08-09",
    actions: ["cancel"],
  },
  {
    name: "Simran Kaur",
    agenda: "Customer Feedback",
    date: "2025-08-10",
    actions: ["call", "cancel"],
  },
  {
    name: "Kunal Puri",
    agenda: "CI/CD Review",
    date: "2025-08-11",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Tanmay Desai",
    agenda: "Release Demo",
    date: "2025-08-12",
    actions: [],
  },
  {
    name: "Mohit Bansal",
    agenda: "Hiring Review",
    date: "2025-08-13",
    actions: ["call"],
  },
  {
    name: "Bhavesh Modi",
    agenda: "SEO Planning",
    date: "2025-08-14",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Ritika Das",
    agenda: "Design Feedback",
    date: "2025-08-15",
    actions: ["call", "cancel"],
  },
  {
    name: "Kriti Sharma",
    agenda: "Bug Triage",
    date: "2025-08-16",
    actions: ["call", "calendar"],
  },
  {
    name: "Uday Kumar",
    agenda: "Marketing Budget",
    date: "2025-08-17",
    actions: ["cancel"],
  },
  {
    name: "Shreya Menon",
    agenda: "UI Testing",
    date: "2025-08-18",
    actions: ["call"],
  },
  {
    name: "Suman Raj",
    agenda: "Team Meeting",
    date: "2025-08-19",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Jatin Arora",
    agenda: "Code Review",
    date: "2025-08-20",
    actions: ["call", "calendar"],
  },
  {
    name: "Rajeev Rana",
    agenda: "Design Approval",
    date: "2025-08-21",
    actions: ["call"],
  },
  {
    name: "Alok Chatterjee",
    agenda: "Hiring Feedback",
    date: "2025-08-22",
    actions: [],
  },
  {
    name: "Trisha Ghosh",
    agenda: "UX Audit",
    date: "2025-08-23",
    actions: ["call", "cancel"],
  },
  {
    name: "Sneha Rao",
    agenda: "Sales Pitch",
    date: "2025-08-24",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Divyansh Tyagi",
    agenda: "Release Meeting",
    date: "2025-08-25",
    actions: ["call"],
  },
  {
    name: "Nikhil Raj",
    agenda: "Performance Review",
    date: "2025-08-26",
    actions: ["call", "calendar"],
  },
  {
    name: "Neeraj Kumar",
    agenda: "Product Strategy",
    date: "2025-08-27",
    actions: ["call", "cancel"],
  },
  {
    name: "Pooja Saini",
    agenda: "Customer Call",
    date: "2025-08-28",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Harshita Yadav",
    agenda: "Technical Training",
    date: "2025-08-29",
    actions: [],
  },
  {
    name: "Deepak Goyal",
    agenda: "Infrastructure Audit",
    date: "2025-08-30",
    actions: ["call", "calendar"],
  },
  {
    name: "Natasha Bedi",
    agenda: "Growth Hacking",
    date: "2025-08-31",
    actions: ["cancel"],
  },
  {
    name: "Yash Agarwal",
    agenda: "Roadmap Discussion",
    date: "2025-09-01",
    actions: ["call"],
  },
  {
    name: "Aarti Joshi",
    agenda: "Sprint Planning",
    date: "2025-09-02",
    actions: ["call", "cancel"],
  },
  {
    name: "Ravi Mehta",
    agenda: "Marketing Campaign",
    date: "2025-09-03",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Siddharth Rao",
    agenda: "Sprint Demo",
    date: "2025-09-04",
    actions: [],
  },
  {
    name: "Ramesh Shah",
    agenda: "User Story Mapping",
    date: "2025-09-05",
    actions: ["call"],
  },
  {
    name: "Divya Nair",
    agenda: "Customer Success",
    date: "2025-09-06",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Manish Roy",
    agenda: "Quarterly Report",
    date: "2025-09-07",
    actions: ["call", "calendar"],
  },
  {
    name: "Ananya Sen",
    agenda: "Project Kickoff",
    date: "2025-09-08",
    actions: ["call"],
  },
  {
    name: "Kajal Mishra",
    agenda: "User Research",
    date: "2025-09-09",
    actions: ["call", "cancel"],
  },
  {
    name: "Rohit Rawat",
    agenda: "Data Sync",
    date: "2025-09-10",
    actions: ["cancel"],
  },
  {
    name: "Ankit Sharma",
    agenda: "Legal Review",
    date: "2025-09-11",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Veer Arora",
    agenda: "Design Feedback",
    date: "2025-09-12",
    actions: ["call", "calendar"],
  },
  {
    name: "Sonal Jain",
    agenda: "Customer Feedback",
    date: "2025-09-13",
    actions: ["call"],
  },
  {
    name: "Kabir Malhotra",
    agenda: "Client Onboarding",
    date: "2025-09-14",
    actions: [],
  },
  {
    name: "Payal Sinha",
    agenda: "Release Meeting",
    date: "2025-09-15",
    actions: ["calendar", "cancel"],
  },
  {
    name: "Meena Verma",
    agenda: "UI Testing",
    date: "2025-09-16",
    actions: ["call", "calendar"],
  },
  {
    name: "Vikas Singh",
    agenda: "PR Review",
    date: "2025-09-17",
    actions: ["call"],
  },
  {
    name: "Keshav Saxena",
    agenda: "Bug Triage",
    date: "2025-09-18",
    actions: ["cancel"],
  },
  {
    name: "Aman Tiwari",
    agenda: "Backend Sync",
    date: "2025-09-19",
    actions: ["call", "calendar"],
  },
  {
    name: "Monika Rani",
    agenda: "Team Meeting",
    date: "2025-09-20",
    actions: ["call"],
  },
  {
    name: "Irfan Khan",
    agenda: "Customer Call",
    date: "2025-09-21",
    actions: ["calendar", "cancel"],
  },
];
